In [1]:
%matplotlib inline 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
games = pd.read_csv('games.csv', sep=',')
games

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3249570,Sotsugyo Omedeto,"Mar 1, 2026",0 - 0,0,0,8.09,0,0,A survival trial game set in an all-girls scho...,"['English', 'Japanese', 'Korean', 'Simplified ...",...,0,0,0,SuperLoki,SuperLoki,"Single-player,Steam Achievements,Camera Comfor...","Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
2218150,Island on cloud,"Feb 24, 2026",0 - 0,0,0,0.59,0,0,"A game with a quirky art style, resembling ani...","['English', 'Simplified Chinese']",...,0,0,0,7th Ghost,7th Ghost,"Single-player,Family Sharing","Adventure,RPG",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
3788650,Rosie Planet,"Mar 1, 2026",0 - 0,0,0,12.99,0,0,Jam Packed full with Videogame Rosie Planet is...,['English'],...,0,0,0,Connor Leary,Connor Leary,"Single-player,Full controller support,Playable...","Action,Adventure,Indie",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
3509140,Fear Effect 2: Retro Helix,"Feb 27, 2026",0 - 0,0,0,9.99,0,0,Return to 2048 Hong Kong in the groundbreaking...,['English'],...,0,0,0,Implicit Conversions,Limited Run Games,"Single-player,Steam Achievements,Full controll...","Action,Adventure",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
4247310,Project Liminal 2,"Mar 2, 2026",0 - 0,0,0,2.51,0,0,All events and characters are fictional. Any r...,"['English', 'Russian', 'Japanese']",...,0,0,0,AquaHeaven Studios,TXC,"Single-player,Steam Achievements,Full controll...","Action,Adventure,Indie",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

In [31]:
games_data = pd.DataFrame(games)
games_data = games_data.reset_index()
games_data.columns = list(games_data.columns[1:]) + ['last_column']
games_data.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,...,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies,last_column
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

In [32]:
games_data.drop('last_column',axis=1,inplace=True)
games_data

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",...,8,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...",...,0,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",...,0,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,...,0,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125850,3249570,Sotsugyo Omedeto,"Mar 1, 2026",0 - 0,0,0,8.09,0,0,A survival trial game set in an all-girls scho...,...,0,0,0,0,SuperLoki,SuperLoki,"Single-player,Steam Achievements,Camera Comfor...","Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...
125851,2218150,Island on cloud,"Feb 24, 2026",0 - 0,0,0,0.59,0,0,"A game with a quirky art style, resembling ani...",...,0,0,0,0,7th Ghost,7th Ghost,"Single-player,Family Sharing","Adventure,RPG",NaN,https://shared.akamai.steamstatic.com/store_it...
125852,3788650,Rosie Planet,"Mar 1, 2026",0 - 0,0,0,12.99,0,0,Jam Packed full with Videogame Rosie Planet is...,...,0,0,0,0,Connor Leary,Connor Leary,"Single-player,Full controller support,Playable...","Action,Adventure,Indie",NaN,https://shared.akamai.steamstatic.com/store_it...
125853,3509140,Fear Effect 2: Retro Helix,"Feb 27, 2026",0 - 0,0,0,9.99,0,0,Return to 2048 Hong Kong in the groundbreaking...,...,0,0,0,0,Implicit Conversions,Limited Run Games,"Single-player,Steam Achievements,Full controll...","Action,Adventure",NaN,https://shared.akamai.steamstatic.com/store_it...
125854,4247310,Project Liminal 2,"Mar 2, 2026",0 - 0,0,0,2.51,0,0,All events and characters are fictional. Any r...,...,0,0,0,0,AquaHeaven Studios,TXC,"Single-player,Steam Achievements,Full controll...","Action,Adventure,Indie",NaN,https://shared.akamai.steamstatic.com/store_it...

In [23]:
games_data.shape

(125855, 39)

In [24]:
games_data.columns

Index(['AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU',
       'Required age', 'Price', 'DiscountDLC count', 'About the game',
       'Supported languages', 'Full audio languages', 'Reviews',
       'Header image', 'Website', 'Support url', 'Support email', 'Windows',
       'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 'User score',
       'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations',
       'Notes', 'Average playtime forever', 'Average playtime two weeks',
       'Median playtime forever', 'Median playtime two weeks', 'Developers',
       'Publishers', 'Categories', 'Genres', 'Tags', 'Screenshots', 'Movies'],
      dtype='str')

In [25]:
games_data.isnull().sum()

AppID                              0
Name                               1
Release date                       0
Estimated owners                   0
Peak CCU                           0
Required age                       0
Price                              0
DiscountDLC count                  0
About the game                     0
Supported languages             8462
Full audio languages               0
Reviews                            0
Header image                  113674
Website                           81
Support url                    75335
Support email                  70560
Windows                        22630
Mac                                0
Linux                              0
Metacritic score                   0
Metacritic url                     0
User score                    121597
Positive                           0
Negative                           0
Score rank                         0
Achievements                  125815
Recommendations                    0
Notes                              0
Average playtime forever      102545
Average playtime two weeks         0
Median playtime forever            0
Median playtime two weeks          0
Developers                         0
Publishers                      8449
Categories                      8922
Genres                          8966
Tags                            8423
Screenshots                    42502
Movies                          6027
dtype: int64